# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 15:13
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('antecedentes', models.CharField(max_length=500)),
                ('examen_dermatologico', models.CharField(max_length=500)),
                ('peso', models.FloatField(default=0)),
                ('estatura', models.FloatField(default=0)),
                ('imc', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cedula', models.CharField(max_length=10)),
                ('sexo', models.CharField(choices=[('f', 'Femenino'), ('m', 'Masculino')], default='f', max_length=1)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('msas', models.CharField(max_length=8)),
                ('cmcs', models.CharField(max_length=8)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FotoDiagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.FileField(upload_to='photos/')),
                ('diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletin.Diagnostico')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_paciente', models.FileField(upload_to=b'', verbose_name='Foto')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('cedula', models.CharField(max_length=10, verbose_name='C\xe9dula')),
                ('nombres', models.CharField(max_length=120)),
                ('apellidos', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electr\xf3nico')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('zona_residencia', models.CharField(max_length=120, verbose_name='Zona Domicilio')),
                ('estado_residencia', models.CharField(choices=[('1', 'Amazonas'), ('2', 'Anzo\xe1tegui'), ('3', 'Apure'), ('4', 'Aragua'), ('5', 'Barinas'), ('6', 'Bol\xedvar'), ('7', 'Carabobo'), ('8', 'Cojedes'), ('9', 'Delta Amacuro'), ('10', 'Falc\xf3n'), ('11', 'Gu\xe1rico'), ('12', 'Lara'), ('13', 'M\xe9rida'), ('14', 'Miranda'), ('15', 'Monagas'), ('16', 'Nueva Esparta'), ('17', 'Portuguesa'), ('18', 'Sucre'), ('19', 'T\xe1chira'), ('20', 'Trujillo'), ('21', 'Vargas'), ('22', 'Yaracuy'), ('23', 'Zulia'), ('24', 'Distrito Capital'), ('25', 'Dependencias Federales')], default='1', max_length=2, verbose_name='Estado Domicilio')),
                ('direccion', models.CharField(max_length=500, verbose_name='Direcci\xf3n')),
                ('telefono_habitacion', models.CharField(blank=True, default=None, max_length=11, verbose_name='Tel\xe9fono Habitaci\xf3n')),
                ('telefono_celular', models.CharField(blank=True, default=None, max_length=11, verbose_name='Tel\xe9fono Celular')),
                ('telefono_trabajo', models.CharField(blank=True, default=None, max_length=11, verbose_name='Tel\xe9fono Trabajo')),
                ('consulta_medicina', models.BooleanField(default=False, verbose_name='Consulta por Medicinas')),
                ('consulta_dermatologia', models.BooleanField(default=False, verbose_name='Consulta Dermatol\xf3gica')),
                ('consulta_alquiler', models.BooleanField(default=False, verbose_name='Consulta por alquiler')),
                ('referencia', models.CharField(default=None, max_length=500)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='boletin.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.CharField(max_length=500)),
                ('indicaciones', models.CharField(max_length=500)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletin.Paciente')),
            ],
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletin.Doctor'),
        ),
        migrations.AddField(
            model_name='diagnostico',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boletin.Paciente'),
        ),
    ]
